#!/bin/bash
# Build script for zrc-platform-ios XCFramework

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Building zrc-platform-ios XCFramework${NC}"

# Check for required tools
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}Error: cargo not found${NC}"
    exit 1
fi

# Install iOS targets if needed
echo -e "${YELLOW}Installing iOS targets...${NC}"
rustup target add aarch64-apple-ios
rustup target add aarch64-apple-ios-sim

# Create output directory
OUTPUT_DIR="target/xcframework"
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Build for iOS device (arm64)
echo -e "${YELLOW}Building for iOS device (aarch64-apple-ios)...${NC}"
cargo build --release --target aarch64-apple-ios

# Build for iOS simulator (arm64)
echo -e "${YELLOW}Building for iOS simulator (aarch64-apple-ios-sim)...${NC}"
cargo build --release --target aarch64-apple-ios-sim

# Create framework directories
DEVICE_FRAMEWORK="$OUTPUT_DIR/ios-arm64/ZrcIos.framework"
SIM_FRAMEWORK="$OUTPUT_DIR/ios-arm64-simulator/ZrcIos.framework"

mkdir -p "$DEVICE_FRAMEWORK/Headers"
mkdir -p "$SIM_FRAMEWORK/Headers"

# Copy headers (generated by UniFFI)
if [ -f "target/aarch64-apple-ios/release/ZrcIos.h" ]; then
    cp "target/aarch64-apple-ios/release/ZrcIos.h" "$DEVICE_FRAMEWORK/Headers/"
    cp "target/aarch64-apple-ios/release/ZrcIos.h" "$SIM_FRAMEWORK/Headers/"
else
    echo -e "${YELLOW}Warning: Headers not found, UniFFI bindings may need to be generated${NC}"
fi

# Copy libraries
cp "target/aarch64-apple-ios/release/libzrc_ios.a" "$DEVICE_FRAMEWORK/ZrcIos"
cp "target/aarch64-apple-ios-sim/release/libzrc_ios.a" "$SIM_FRAMEWORK/ZrcIos"

# Create Info.plist files
cat > "$DEVICE_FRAMEWORK/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>ZrcIos</string>
    <key>CFBundleIdentifier</key>
    <string>io.zippyremote.zrc-ios</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundlePackageType</key>
    <string>FMWK</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
</dict>
</plist>
EOF

cp "$DEVICE_FRAMEWORK/Info.plist" "$SIM_FRAMEWORK/Info.plist"

# Create XCFramework
echo -e "${YELLOW}Creating XCFramework...${NC}"
xcodebuild -create-xcframework \
    -framework "$DEVICE_FRAMEWORK" \
    -framework "$SIM_FRAMEWORK" \
    -output "$OUTPUT_DIR/ZrcIos.xcframework"

echo -e "${GREEN}✓ XCFramework created at: $OUTPUT_DIR/ZrcIos.xcframework${NC}"
