//! ZRC Platform iOS - Rust library for iOS controller application
//!
//! This crate provides UniFFI bindings to expose ZRC core functionality
//! to Swift/SwiftUI applications on iOS.

mod core;
mod error;
mod frame;
mod input;

// Re-export main types
pub use core::ZrcCore;
pub use error::ZrcError;
pub use frame::FrameData;
pub use input::{InputEvent, MouseButton};

// Include UniFFI scaffolding (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/zrc_ios.uniffi.rs"));
