#![forbid(unsafe_code)]

pub mod v1 {
    // Generated by prost at build time.
    include!(concat!(env!("OUT_DIR"), "/zrc.v1.rs"));
}

pub mod validation;
pub mod conversions;

#[cfg(test)]
mod proptests;

// Re-export validation types at crate root for convenience
pub use validation::{Validate, ValidationError, ValidationResult};

// Re-export conversion types at crate root for convenience
pub use conversions::Permissions;
